### PR TITLE
Bump pronto version to 0.7.0

### PR DESCRIPTION
**Pull request by dennmart**
This pull request is to bump up the version of Pronto to 0.7.0 and above. Pronto was updated to version 0.7.0 a few weeks ago.

This runner is the only Pronto runner that I use that still hasn't bumped up their version, so hopefully this will encourage a gem update very soon :smile_cat:

### CODE REVIEW

**Comment by dennmart** [comment]
@raimondasv The build is failing on the Ruby 1.9.3 specs because [Pronto now requires Ruby 2.0.0 and above](https://github.com/mmozuras/pronto/commit/9b5e9face502cb1b5fdcb852fd7d955e3f261a16). Seems like other Pronto runners are following suit. If that's the case, this gem should also deprecate Ruby 1.9.3 and only support Ruby 2.0.0 and above.

**Comment by dennmart** [comment]
@raimondasv I updated this branch to explicitly support Ruby 2.0.0 for the gem, and I updated the test matrix to include the latest Ruby 2.x versions for testing. Everything is green now!

**Comment by raimondasv** [comment]
Thanks!

**Comment by raimondasv** [comment]
@dennmart I've just published 0.7.0 version gem.

**Comment by dennmart** [comment]
Thanks for the prompt merging and gem update! :+1:

**Pull request merged**
